-- MySQL Script generated by MySQL Workbench
-- Wed May  1 14:07:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema xpost_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xpost_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xpost_db` DEFAULT CHARACTER SET utf8 ;
USE `xpost_db` ;

-- -----------------------------------------------------
-- Table `xpost_db`.`x_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpost_db`.`x_accounts` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `account_id` VARCHAR(32) NOT NULL COMMENT '一意の識別子',
  `name` VARCHAR(256) NOT NULL COMMENT 'フレンドリーネーム（表示名）',
  `username` VARCHAR(256) NOT NULL COMMENT 'スクリーンネーム',
  `last_login` DATETIME NOT NULL COMMENT '最終ログイン日時',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Xアカウント';


-- -----------------------------------------------------
-- Table `xpost_db`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpost_db`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `x_accounts_id` INT NOT NULL COMMENT 'XアカウントID',
  `tweet_id` VARCHAR(32) NOT NULL COMMENT '投稿ID',
  `tweet_text` TEXT NOT NULL COMMENT '本文',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`),
  INDEX `fk_posts_x_accounts_idx` (`x_accounts_id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '投稿';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
